pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                // Клонируем репозиторий с ветки main
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[url: 'https://github.com/olovekb/urfu_AutoML.git']]
                ])
            }
        }
        stage('Install Dependencies') {
            steps {
                // Создаём виртуальное окружение
                bat ' "C:\\Users\\SHEM\\AppData\\Local\\Programs\\Python\\Python312\\python.exe" python -m venv venv'
                
                // Обновляем pip
                bat 'venv\\Scripts\\python.exe -m pip install --upgrade pip'
                
                // Устанавливаем зависимости из lab2/requirements.txt
                bat 'venv\\Scripts\\python.exe -m pip install -r lab2\\requirements.txt'
            }
        }
        stage('Run data_creation.py') {
            steps {
                bat 'venv\\Scripts\\python.exe lab1\\data_creation.py'
            }
        }
        stage('Run data_preprocessing.py') {
            steps {
                bat 'venv\\Scripts\\python.exe lab1\\data_preprocessing.py'
            }
        }
        stage('Run model_preparation.py') {
            steps {
                bat 'venv\\Scripts\\python.exe lab1\\model_preparation.py'
            }
        }
        stage('Run model_testing.py') {
            steps {
                bat 'venv\\Scripts\\python.exe lab1\\model_testing.py'
            }
        }
    }
}
