version: '3.8'

services:
  streamlit_app:
    build:
      context: .
      args:
        COMMIT_SHA: ${COMMIT_SHA:-latest}
        BRANCH_NAME: ${BRANCH_NAME:-local}
    image: shoolife/streamlit_app:${COMMIT_SHA:-latest}
    ports:
      - "8501:8501"
